development:
  adapter: postgresql
  encoding: unicode
  database: affiliate_site_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: affiliate_site_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: affiliate_site_production
  pool: 5
  username: affiliate_site
  password: